/* eslint-disable react/no-unescaped-entities */
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BPBKchCrPBN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function ArticleDetails() {
  return (
    <div className="bg-background text-foreground">
      <div className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
        <article className="prose prose-gray dark:prose-invert">
          <div className="space-y-2 not-prose">
            <h1 className="text-4xl font-extrabold tracking-tight lg:text-5xl lg:leading-[3.5rem]">
              The Spiritual Journey of Umrah and Hajj
            </h1>
            <div className="flex items-center space-x-4">
              <div className="flex items-center space-x-2">
                <Avatar>
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>AA</AvatarFallback>
                </Avatar>
                <div>
                  <div className="font-medium">Aisha Ahmed</div>
                  <div className="text-sm text-muted-foreground">Religious Writer</div>
                </div>
              </div>
              <div className="text-sm text-muted-foreground">Published on July 15, 2023</div>
            </div>
          </div>
          <p>
            Umrah and Hajj are two of the most significant spiritual journeys in the Islamic faith. These pilgrimages
            hold immense significance for Muslims, as they provide an opportunity to connect with the divine, seek
            forgiveness, and deepen their spiritual connection.
          </p>
          <p>
            The Umrah, often referred to as the "minor pilgrimage," is a voluntary journey to the holy sites of Mecca
            and Medina. It can be performed at any time of the year, and it is a deeply personal experience that allows
            individuals to immerse themselves in the sacred atmosphere of these holy cities.
          </p>
          <p>
            The Hajj, on the other hand, is the "major pilgrimage" and is one of the five pillars of Islam. It is a
            mandatory duty for every Muslim who is physically and financially able to undertake the journey. The Hajj
            takes place annually during the 12th month of the Islamic calendar, and it involves a series of rituals and
            activities that are deeply rooted in the life and teachings of the Prophet Muhammad (peace be upon him).
          </p>
          <p>
            During both the Umrah and Hajj, pilgrims engage in a range of spiritual practices, such as circling the
            Kaaba, performing the tawaf, and praying at the Masjid al-Haram and the Masjid an-Nabawi. These rituals are
            not merely physical acts but rather a means of connecting with the divine, seeking forgiveness, and renewing
            one`s commitment to the faith.
          </p>
          <p>
            The journey of Umrah and Hajj is not just about the physical pilgrimage; it is a transformative experience
            that can have a profound impact on the individual`s spiritual and emotional well-being. Pilgrims often
            return from these journeys with a renewed sense of purpose, a deeper understanding of their faith, and a
            stronger connection to the global Muslim community.
          </p>
          <p>
            In conclusion, the spiritual journey of Umrah and Hajj is a testament to the depth and richness of the
            Islamic faith. It provides an opportunity for Muslims to connect with the divine, seek forgiveness, and
            deepen their spiritual connection, ultimately leading to a more fulfilling and meaningful life.
          </p>
        </article>
        <div className="mt-12 border-t border-muted pt-6">
          <h2 className="text-2xl font-bold">Comments</h2>
          <div className="mt-6 space-y-6">
            <div className="flex items-start space-x-4">
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>JD</AvatarFallback>
              </Avatar>
              <div className="flex-1">
                <div className="flex items-center justify-between">
                  <div className="font-medium">John Doe</div>
                  <div className="text-sm text-muted-foreground">July 16, 2023</div>
                </div>
                <p className="mt-2">
                  This article was a beautiful and insightful read. The description of the spiritual journey of Umrah
                  and Hajj was truly inspiring. I feel a deeper appreciation for these important pilgrimages in the
                  Islamic faith.
                </p>
              </div>
            </div>
            <div className="flex items-start space-x-4">
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>SA</AvatarFallback>
              </Avatar>
              <div className="flex-1">
                <div className="flex items-center justify-between">
                  <div className="font-medium">Sarah Ahmed</div>
                  <div className="text-sm text-muted-foreground">July 17, 2023</div>
                </div>
                <p className="mt-2">
                  As someone who has performed both Umrah and Hajj, I can attest to the profound impact these
                  pilgrimages have had on my spiritual life. The article captures the essence of these journeys
                  beautifully. I`m grateful to have had the opportunity to undertake these sacred experiences.
                </p>
              </div>
            </div>
            <div className="flex items-start space-x-4">
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>MA</AvatarFallback>
              </Avatar>
              <div className="flex-1">
                <div className="flex items-center justify-between">
                  <div className="font-medium">Muhammad Ali</div>
                  <div className="text-sm text-muted-foreground">July 18, 2023</div>
                </div>
                <p className="mt-2">
                  This article is a wonderful resource for those interested in learning more about the spiritual
                  significance of Umrah and Hajj. The author has done an excellent job of explaining the key aspects of
                  these pilgrimages in a clear and engaging manner. I highly recommend this read.
                </p>
              </div>
            </div>
            <div className="flex items-start space-x-4">
              <Avatar>
                <AvatarImage src="/placeholder-user.jpg" />
                <AvatarFallback>FZ</AvatarFallback>
              </Avatar>
              <div className="flex-1">
                <div className="flex items-center justify-between">
                  <div className="font-medium">Fatima Zahra</div>
                  <div className="text-sm text-muted-foreground">July 19, 2023</div>
                </div>
                <p className="mt-2">
                  As a Muslim, I found this article to be a beautiful and insightful exploration of the spiritual
                  journey of Umrah and Hajj. The author's descriptions of the rituals and their deeper meanings were
                  both informative and inspiring. I'm grateful for this thoughtful and well-written piece.
                </p>
              </div>
            </div>
          </div>
          <div className="mt-8">
            <h3 className="text-xl font-bold">Leave a Comment</h3>
            <form className="mt-4 grid gap-4">
              <div className="grid gap-2">
                <Label htmlFor="name">Name</Label>
                <Input id="name" type="text" placeholder="Enter your name" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" type="email" placeholder="Enter your email" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="comment">Comment</Label>
                <Textarea id="comment" placeholder="Write your comment here..." className="min-h-[120px]" />
              </div>
              <Button type="submit">Submit Comment</Button>
            </form>
          </div>
        </div>
      </div>
    </div>
  )
}
