/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Q1A1oIYgrvK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'
import { DM_Serif_Display } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

dm_serif_display({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card, CardContent } from "@/components/ui/card"
import Image from "next/image"

export function Courses() {
  return (
    <div className="flex flex-col">
      <section className="bg-primary py-20 md:py-32">
        <div className="container mx-auto px-4 md:px-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12 items-center">
            <div className="space-y-4 md:space-y-6">
              <h1 className="text-3xl md:text-5xl font-bold text-primary-foreground">
                Discover the Wonders of Umra and Hajj
              </h1>
              <p className="text-lg md:text-xl text-primary-foreground">
                Embark on a spiritual journey with our comprehensive guide to Umra and Hajj for beginners.
              </p>
              <Link
                href="#"
                className="inline-flex items-center justify-center rounded-md bg-primary-foreground px-8 py-3 text-sm md:text-base font-medium text-primary shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-1 focus:ring-primary focus:ring-offset-1"
                prefetch={false}
              >
                Get Started
              </Link>
            </div>
            <div className="hidden md:block">
              <Image src="/landing.jpg" width={600} height={400} alt="Umra and Hajj" className="rounded-lg" />
            </div>
          </div>
        </div>
      </section>
      <section className="py-12 md:py-20">
        <div className="container mx-auto px-4 md:px-6">
          <div className="space-y-4 md:space-y-6 text-center">
            <h2 className="text-2xl md:text-4xl font-bold">Explore Our Courses</h2>
            <p className="text-lg md:text-xl text-muted-foreground">
              Learn everything you need to know about Umra and Hajj.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 md:gap-8 mt-8 md:mt-12">
            <Card>
              <Image src="/landing2.jpg" width={300} height={200} alt="Umra Rituals" className="rounded-t-lg" />
              <CardContent className="p-4 md:p-6">
                <h3 className="text-xl font-bold">Umra Rituals</h3>
                <p className="text-muted-foreground mt-2">
                  Discover the sacred rituals and traditions of the Umra pilgrimage.
                </p>
                <Link
                  href="#"
                  className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm md:text-base font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-1 focus:ring-primary focus:ring-offset-1 mt-4"
                  prefetch={false}
                >
                  Learn More
                </Link>
              </CardContent>
            </Card>
            <Card>
              <Image src="/landing3.jpg" width={300} height={200} alt="Hajj Preparation" className="rounded-t-lg" />
              <CardContent className="p-4 md:p-6">
                <h3 className="text-xl font-bold">Hajj Preparation</h3>
                <p className="text-muted-foreground mt-2">
                  Get ready for the Hajj pilgrimage with our comprehensive guide.
                </p>
                <Link
                  href="#"
                  className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm md:text-base font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-1 focus:ring-primary focus:ring-offset-1 mt-4"
                  prefetch={false}
                >
                  Learn More
                </Link>
              </CardContent>
            </Card>
            <Card>
              <Image src="/landing.jpg" width={300} height={200} alt="Hajj Etiquette" className="rounded-t-lg" />
              <CardContent className="p-4 md:p-6">
                <h3 className="text-xl font-bold">Hajj Etiquette</h3>
                <p className="text-muted-foreground mt-2">
                  Learn the proper etiquette and customs to observe during the Hajj.
                </p>
                <Link
                  href="#"
                  className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm md:text-base font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-1 focus:ring-primary focus:ring-offset-1 mt-4"
                  prefetch={false}
                >
                  Learn More
                </Link>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </div>
  )
}
