/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bv8a2xOWWcy
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 *
 *
 */

import Image from "next/image";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function landing() {
  return (
    <div className="flex flex-col min-h-dvh bg-background text-foreground">
      <header className="px-4 lg:px-6 h-14 flex items-center border-b">
        <Link
          href="#"
          className="flex items-center justify-center"
          prefetch={false}
        >
          <KeyIcon className="w-6 h-6" />
          <span className="sr-only">HajjJourney</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            href="/articles"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            About Hajj
          </Link>

          <Link
            href="/courses"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Courses
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Checklist
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Resources
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full flex justify-center py-12 md:py-24 lg:py-32 border-b">
          <div className="container space-y-10 px-4 md:px-6">
            <div className="grid max-w-[1300px] mx-auto gap-4 px-4 sm:px-6 md:px-10 md:grid-cols-2 md:gap-16">
              <div>
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  Your Trusted Companion for the Hajj Journey
                </h1>
                <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl">
                  Discover essential information, plan your pilgrimage, and
                  navigate the Hajj with ease.
                </p>
              </div>
              <div className="flex flex-col items-start space-y-4">
                <Button size="lg" className="w-full sm:w-auto">
                  <Link href="/articles" >
                  Explore Hajj
                  </Link>
                </Button>
                <Button
                  variant="outline"
                  size="lg"
                  className="w-full sm:w-auto"
                >
                  <Link href="https://hickmet.kz/">Find Tours</Link>
                </Button>
                <Button
                  variant="outline"
                  size="lg"
                  className="w-full sm:w-auto"
                >
                  <Link href="/courses">Courses</Link>
                </Button>
              </div>
            </div>
            <Image
              src="/landing.jpg"
              width="1270"
              height="300"
              alt="Hajj"
              className="mx-auto aspect-[3/1] overflow-hidden rounded-t-xl object-cover"
            />
          </div>
        </section>
        <section className="w-full flex justify-center py-12 md:py-24 lg:py-32">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Understand the Hajj
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Explore the significance, rituals, and important sites of the
                  Hajj pilgrimage.
                </p>
              </div>
            </div>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Significance of Hajj</h3>
                <p className="text-sm text-muted-foreground">
                  Understand the spiritual and religious importance of the Hajj
                  pilgrimage.
                </p>
                <Link
                  href="#"
                  className="font-medium text-primary"
                  prefetch={false}
                >
                  Learn More
                </Link>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Hajj Rituals</h3>
                <p className="text-sm text-muted-foreground">
                  Explore the key rituals and practices performed during the
                  Hajj.
                </p>
                <Link
                  href="#"
                  className="font-medium text-primary"
                  prefetch={false}
                >
                  Learn More
                </Link>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Important Hajj Sites</h3>
                <p className="text-sm text-muted-foreground">
                  Discover the sacred locations and landmarks of the Hajj
                  pilgrimage.
                </p>
                <Link
                  href="#"
                  className="font-medium text-primary"
                  prefetch={false}
                >
                  Learn More
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full flex justify-center py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Plan Your Hajj Journey
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Explore approved tour packages, check the Hajj schedule, and
                  stay on top of your preparations.
                </p>
              </div>
            </div>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Hajj Schedule</h3>
                <p className="text-sm text-muted-foreground">
                  Stay up-to-date with the schedule of Hajj activities and
                  events.
                </p>
                <Link
                  href="#"
                  className="font-medium text-primary"
                  prefetch={false}
                >
                  View Schedule
                </Link>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Tour Packages</h3>
                <p className="text-sm text-muted-foreground">
                  Explore approved tour operators and compare Hajj package
                  options.
                </p>
                <Link
                  href="#"
                  className="font-medium text-primary"
                  prefetch={false}
                >
                  Find Tours
                </Link>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Hajj Checklist</h3>
                <p className="text-sm text-muted-foreground">
                  Keep track of your Hajj preparations with a comprehensive
                  checklist.
                </p>
                <Link
                  href="#"
                  className="font-medium text-primary"
                  prefetch={false}
                >
                  View Checklist
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full flex justify-center py-12 md:py-24 lg:py-32">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Stay Connected and Informed
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Access prayer times, explore the Hajj map, and find emergency
                  resources for your pilgrimage.
                </p>
              </div>
            </div>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Prayer Times</h3>
                <p className="text-sm text-muted-foreground">
                  Stay on top of your prayers with real-time prayer timings
                  based on your location.
                </p>
                <Link
                  href="#"
                  className="font-medium text-primary"
                  prefetch={false}
                >
                  Check Prayer Times
                </Link>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Hajj Map</h3>
                <p className="text-sm text-muted-foreground">
                  Explore the locations of important Hajj sites and landmarks on
                  an interactive map.
                </p>
                <Link
                  href="#"
                  className="font-medium text-primary"
                  prefetch={false}
                >
                  View Map
                </Link>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Emergency Resources</h3>
                <p className="text-sm text-muted-foreground">
                  Access important contact information and resources for
                  emergencies during your Hajj.
                </p>
                <Link
                  href="#"
                  className="font-medium text-primary"
                  prefetch={false}
                >
                  Explore Resources
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full flex justify-center py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Q&A
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Get answers to your questions about the Hajj pilgrimage.
                </p>
              </div>
            </div>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">What is the Hajj?</h3>
                <p className="text-sm text-muted-foreground">
                  The Hajj is the annual Islamic pilgrimage to Mecca, the
                  holiest city in Islam. It is a religious duty for Muslims to
                  perform at least once in their lifetime.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">
                  When does the Hajj take place?
                </h3>
                <p className="text-sm text-muted-foreground">
                  The Hajj takes place during the 12th month of the Islamic
                  calendar, known as Dhu al-Hijjah. The specific dates vary each
                  year, but it typically occurs in the summer months.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">
                  What are the main Hajj rituals?
                </h3>
                <p className="text-sm text-muted-foreground">
                  The main Hajj rituals include wearing the ihram (white
                  garments), performing the tawaf (circling the Kaaba), standing
                  on Mount Arafat, and throwing stones at the Jamarat (pillars).
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">
                  How long does the Hajj last?
                </h3>
                <p className="text-sm text-muted-foreground">
                  The Hajj typically lasts around 5-6 days, but the entire
                  journey, including travel to and from Mecca, can take several
                  weeks.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">
                  What is the significance of the Hajj?
                </h3>
                <p className="text-sm text-muted-foreground">
                  The Hajj is a profound spiritual experience for Muslims,
                  symbolizing the unity of the global Islamic community and the
                  equality of all believers before God.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">
                  How can I prepare for the Hajj?
                </h3>
                <p className="text-sm text-muted-foreground">
                  Preparation for the Hajj includes obtaining the necessary
                  visas and permits, arranging for transportation and
                  accommodation, and ensuring you have the proper attire and
                  supplies. It`s also important to prepare spiritually and
                  mentally for the journey.
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">
          &copy; 2024 HajjJourney. All rights reserved.
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}
          >
            Terms of Service
          </Link>
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}
          >
            Privacy
          </Link>
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}
          >
            Contact
          </Link>
        </nav>
      </footer>
    </div>
  );
}

function KeyIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15.5 7.5 2.3 2.3a1 1 0 0 0 1.4 0l2.1-2.1a1 1 0 0 0 0-1.4L19 4" />
      <path d="m21 2-9.6 9.6" />
      <circle cx="7.5" cy="15.5" r="5.5" />
    </svg>
  );
}

function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
